title: "🚀 Mi Página en GitHub"
author: "Tu Nombre"
description: "Portafolio de proyectos, tecnología y más. ¡Explora mi trabajo!"
theme: jekyll-theme-cayman
show_downloads: true
logo: "/assets/img/logo.png"
